params:
  epochs: 30
  batch_size: 32
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  num_classes: 10


artifacts:
  artifacts_dir: artifacts
  model_dr: model
  plots: plots
  checkpoint_dir: checkpoints


logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs